version: '3.4'

volumes:
  egress_program_db_volume:
  seq_volume:

networks:
  backend:

services:

  egress_program_db:
    ports:
      - "1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=Abcd@1234
    volumes:
      - egress_program_db_volume:/var/opt/mssql
    networks:
      - backend

  auth_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - backend

  egress_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - backend

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5341:80"
    volumes:
      - seq_volume:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - backend