version: '3.4'

volumes:
  authapp_db_volume:
  jobapp_db_volume:
  egressapp_db_volume:

networks:
  backend:

services:
#  apigateway:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://+:80
#    ports:
#      - "80"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
#    networks:
#      - backend
#
  auth_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - backend

  auth_db:
    ports:
      - "1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd@1234
    volumes:
      - authapp_db_volume:/var/opt/mssql
    networks:
      - backend

  job_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - backend
  
  job_db:
    ports:
      - "1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd@1234
    volumes:
      - jobapp_db_volume:/var/opt/mssql
    networks:
      - backend

  egress_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
    networks:
      - backend

  egress_db:
    ports:
      - "1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd@1234
    volumes:
      - egressapp_db_volume:/var/opt/mssql
    networks:
      - backend