version: '3.4'

services:
  egress_program_db:
    container_name: egress_program_db
    image: mcr.microsoft.com/azure-sql-edge
    ports:  
      - "9000:1433"

  auth_api:
    container_name: auth_api
    image: ${DOCKER_REGISTRY-}authappapi
    build:
      context: .
      dockerfile: src/microservices/AuthApp/API/AuthApp.API/Dockerfile
    ports:
      - "5010:80"
    depends_on:
      - egress_program_db

  egress_api:
    container_name: egress_api
    image: ${DOCKER_REGISTRY-}egressapi
    build:
      context: .
      dockerfile: src/microservices/EgressApp/Egress.API/Dockerfile
    ports:
      - "5020:80"
