//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthApp.Infra.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthApp.Infra.CrossCutting.Resources.ErrorCodeResource", typeof(ErrorCodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business failure.
        /// </summary>
        public static string BUSINESS_FAILURE {
            get {
                return ResourceManager.GetString("BUSINESS_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0003: Confirm your account.
        /// </summary>
        public static string CONFIRM_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0010: Could not change password.
        /// </summary>
        public static string COULD_NOT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("COULD_NOT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0007: Could not confirm account.
        /// </summary>
        public static string COULD_NOT_CONFIRM {
            get {
                return ResourceManager.GetString("COULD_NOT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0013: Could not define role.
        /// </summary>
        public static string COULD_NOT_DEFINE_ROLE {
            get {
                return ResourceManager.GetString("COULD_NOT_DEFINE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0015: Could not reset password.
        /// </summary>
        public static string COULD_NOT_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("COULD_NOT_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data validation failure.
        /// </summary>
        public static string DATA_VALIDATION_FAILURE {
            get {
                return ResourceManager.GetString("DATA_VALIDATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB0002: Could not get refresh token to delete.
        /// </summary>
        public static string DB_COULD_NOT_GET_REFRESHTOKEN_TO_DELETE {
            get {
                return ResourceManager.GetString("DB_COULD_NOT_GET_REFRESHTOKEN_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB0001: Could not get refresh token to update.
        /// </summary>
        public static string DB_COULD_NOT_GET_REFRESHTOKEN_TO_UPDATE {
            get {
                return ResourceManager.GetString("DB_COULD_NOT_GET_REFRESHTOKEN_TO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0014: Email not informed.
        /// </summary>
        public static string EMAIL_NOT_INFORMED {
            get {
                return ResourceManager.GetString("EMAIL_NOT_INFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0017: There was an error generating the tokens.
        /// </summary>
        public static string ERROR_GENERATING_TOKENS {
            get {
                return ResourceManager.GetString("ERROR_GENERATING_TOKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error generating the tokens.
        /// </summary>
        public static string ERROR_GENERATING_TOKENS_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_GENERATING_TOKENS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0012: Refresh token has expired.
        /// </summary>
        public static string EXPIRED_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("EXPIRED_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0019: Invalid authorization token.
        /// </summary>
        public static string INVALID_AUTHORIZATION_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_AUTHORIZATION_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0001: Invalid credentials.
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0008: Invalid parameters.
        /// </summary>
        public static string INVALID_PARAMETERS {
            get {
                return ResourceManager.GetString("INVALID_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0009: Invalid password.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0016: Invalid refresh token.
        /// </summary>
        public static string INVALID_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0011: Token with invalid format.
        /// </summary>
        public static string INVALID_TOKEN_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_TOKEN_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIL0001: There was an error sending the email.
        /// </summary>
        public static string MAIL_ERROR_SENDING_EMAIL {
            get {
                return ResourceManager.GetString("MAIL_ERROR_SENDING_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BU0001: It was not possible to identify the egress. I recommend contacting the collegiate..
        /// </summary>
        public static string NOT_IDENTITY_EGRESS {
            get {
                return ResourceManager.GetString("NOT_IDENTITY_EGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0018: refresh_token header is required.
        /// </summary>
        public static string REFRESH_TOKEN_HEADER_REQUIRED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_HEADER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0006: Could not register user.
        /// </summary>
        public static string REGISTER_COULD_NOT_REGISTER_USER {
            get {
                return ResourceManager.GetString("REGISTER_COULD_NOT_REGISTER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0005: User already exists.
        /// </summary>
        public static string REGISTER_USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("REGISTER_USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR0001: An unexpected error occurred.
        /// </summary>
        public static string UNEXPECTED_ERROR_OCURRED {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR_OCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0002: User is blocked.
        /// </summary>
        public static string USER_IS_BLOCKED {
            get {
                return ResourceManager.GetString("USER_IS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH0004: User not found.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA0002: {PropertyName} can&apos;t be empty.
        /// </summary>
        public static string VALIDATION_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA0001: {PropertyName} can&apos;t be null.
        /// </summary>
        public static string VALIDATION_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("VALIDATION_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA0003: Invalid {PropertyName}.
        /// </summary>
        public static string VALIDATION_INVALID_PROPERTY {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA0004: {PropertyName} is not equal.
        /// </summary>
        public static string VALIDATION_NOT_EQUAL_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_EQUAL_PASSWORD", resourceCulture);
            }
        }
    }
}
