//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthApp.Infra.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodeResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthApp.Infra.CrossCutting.Resources.ErrorCodeResource", typeof(ErrorCodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0003: Confirm your account.
        /// </summary>
        public static string CONFIRM_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0010: Could not change password.
        /// </summary>
        public static string COULD_NOT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("COULD_NOT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0007: Could not confirm account.
        /// </summary>
        public static string COULD_NOT_CONFIRM {
            get {
                return ResourceManager.GetString("COULD_NOT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0013: Could not define role.
        /// </summary>
        public static string COULD_NOT_DEFINE_ROLE {
            get {
                return ResourceManager.GetString("COULD_NOT_DEFINE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0015: Could not reset password.
        /// </summary>
        public static string COULD_NOT_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("COULD_NOT_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DB0002: Could not get refresh token to delete.
        /// </summary>
        public static string DB_COULD_NOT_GET_REFRESHTOKEN_TO_DELETE {
            get {
                return ResourceManager.GetString("DB_COULD_NOT_GET_REFRESHTOKEN_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DB0001: Could not get refresh token to update.
        /// </summary>
        public static string DB_COULD_NOT_GET_REFRESHTOKEN_TO_UPDATE {
            get {
                return ResourceManager.GetString("DB_COULD_NOT_GET_REFRESHTOKEN_TO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0014: Email not informed.
        /// </summary>
        public static string EMAIL_NOT_INFORMED {
            get {
                return ResourceManager.GetString("EMAIL_NOT_INFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0017: There was an error generating the tokens.
        /// </summary>
        public static string ERROR_GENERATING_TOKENS {
            get {
                return ResourceManager.GetString("ERROR_GENERATING_TOKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0012: Refresh token has expired.
        /// </summary>
        public static string EXPIRED_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("EXPIRED_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0001: Invalid credentials.
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0008: Invalid parameters.
        /// </summary>
        public static string INVALID_PARAMETERS {
            get {
                return ResourceManager.GetString("INVALID_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0009: Invalid password.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0016: Invalid refresh token.
        /// </summary>
        public static string INVALID_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0011: Token with invalid format.
        /// </summary>
        public static string INVALID_TOKEN_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_TOKEN_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MAIL0001: There was an error sending the email.
        /// </summary>
        public static string MAIL_ERROR_SENDING_EMAIL {
            get {
                return ResourceManager.GetString("MAIL_ERROR_SENDING_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0018: refresh_token header is required.
        /// </summary>
        public static string REFRESH_TOKEN_HEADER_REQUIRED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_HEADER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0006: Could not register user.
        /// </summary>
        public static string REGISTER_COULD_NOT_REGISTER_USER {
            get {
                return ResourceManager.GetString("REGISTER_COULD_NOT_REGISTER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0005: User already exists.
        /// </summary>
        public static string REGISTER_USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("REGISTER_USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ERROR0001: An unexpected error occurred.
        /// </summary>
        public static string UNEXPECTED_ERROR_OCURRED {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR_OCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0002: User is blocked.
        /// </summary>
        public static string USER_IS_BLOCKED {
            get {
                return ResourceManager.GetString("USER_IS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AUTH0004: User not found.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VA0002: {PropertyName} can&apos;t be empty.
        /// </summary>
        public static string VALIDATION_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VA0001: {PropertyName} can&apos;t be null.
        /// </summary>
        public static string VALIDATION_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("VALIDATION_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VA0003: Invalid {PropertyName}.
        /// </summary>
        public static string VALIDATION_INVALID_PROPERTY {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VA0004: {PropertyName} is not equal.
        /// </summary>
        public static string VALIDATION_NOT_EQUAL_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_EQUAL_PASSWORD", resourceCulture);
            }
        }
    }
}
