//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthApp.Infra.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplatesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplatesResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthApp.Infra.CrossCutting.Resources.TemplatesResource", typeof(TemplatesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div style=&quot;max-width:550px;color:rgb(230, 233, 255);background-color:#0C1F2F;border-top:5px solid #17A27F;border-bottom:5px solid #17A27F;margin:40px auto;width: 70%;text-align: center;padding:50px 0;&quot;&gt;
        ///    &lt;img alt=&quot;uesc logo&quot; src=&quot;https://i.imgur.com/YAyKnRy.png&quot; style=&quot;height:78px; width:60px&quot; /&gt;
        ///    
        ///    &lt;div style=&quot;padding:20px 0;&quot;&gt;
        ///        &lt;h1 style=&quot;color:#FFCC29;margin:0;font-family:&apos;Franklin Gothic Medium&apos;, &apos;Arial Narrow&apos;, Arial, sans-serif;&quot;&gt;Olá {0}&lt;/h1&gt;
        ///        &lt;h3 style=&quot;color:#FFCC29;marg [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string CONFIRMED_EMAIL_RESET_PASSWORD_MESSAGE {
            get {
                return ResourceManager.GetString("CONFIRMED_EMAIL_RESET_PASSWORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha redefinida com sucesso.
        /// </summary>
        public static string CONFIRMED_EMAIL_RESET_PASSWORD_SUBJECT {
            get {
                return ResourceManager.GetString("CONFIRMED_EMAIL_RESET_PASSWORD_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div style=&quot;max-width:550px;color:rgb(230, 233, 255);background-color:#0C1F2F;border-top:5px solid #17A27F;border-bottom:5px solid #17A27F;margin:40px auto;width: 70%;text-align: center;padding:50px 0;&quot;&gt;
        ///    &lt;img alt=&quot;uesc logo&quot; src=&quot;https://i.imgur.com/YAyKnRy.png&quot; style=&quot;height:78px; width:60px&quot; /&gt;
        ///    
        ///    &lt;div style=&quot;padding: 2px 0;&quot;&gt;
        ///        &lt;h1 style=&quot;color:#FFCC29;margin:20px 0 0;font-family:&apos;Franklin Gothic Medium&apos;, &apos;Arial Narrow&apos;, Arial, sans-serif;&quot;&gt;Olá {0}&lt;/h1&gt;
        ///        &lt;h2 style=&quot;color:#FFCC [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string EMAIL_CONFIRM_MESSAGE {
            get {
                return ResourceManager.GetString("EMAIL_CONFIRM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação de Email.
        /// </summary>
        public static string EMAIL_CONFIRM_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_CONFIRM_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div style=&quot;max-width:550px;color:rgb(230, 233, 255);background-color:#0C1F2F;border-top:5px solid #17A27F;border-bottom:5px solid #17A27F;margin:40px auto;width: 70%;text-align: center;padding:50px 0;&quot;&gt;
        ///    &lt;img alt=&quot;uesc logo&quot; src=&quot;https://i.imgur.com/YAyKnRy.png&quot; style=&quot;height:78px; width:60px&quot; /&gt;
        ///    
        ///    &lt;div style=&quot;padding:20px 0;&quot;&gt;
        ///        &lt;h1 style=&quot;color:#FFCC29;margin:0;font-family:&apos;Franklin Gothic Medium&apos;, &apos;Arial Narrow&apos;, Arial, sans-serif;&quot;&gt;Olá {0}&lt;/h1&gt;
        ///        &lt;p style=&quot;color:white;margin: [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string EMAIL_RESET_PASSWORD_MESSAGE {
            get {
                return ResourceManager.GetString("EMAIL_RESET_PASSWORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Redefinir sua senha.
        /// </summary>
        public static string EMAIL_RESET_PASSWORD_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_RESET_PASSWORD_SUBJECT", resourceCulture);
            }
        }
    }
}
